# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# instructions

version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  image: darklotus/nerds-microfinance:latest
  build: .
  depends_on:
    - redis
    - postgres
  command: ["start_app.sh"]
  env_file: .env
  environment:
    FLASK_DEBUG: 1 # set this to 0 to disable debug mode
    FLASK_APP: manage.py
  volumes:
    - .:/opt/apps/app

services:
  redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  postgres:
    restart: unless-stopped
    image: postgres:11
    environment:
      POSTGRES_USER: apps
      POSTGRES_PASSWORD: apps_pass
      POSTGRES_DB: nerds_microfinance

  web:
    <<: *defaults
    ports:
      - '0.0.0.0:8000:8000'

  worker:
    <<: *defaults
    command: ["start_worker.sh"]
